# Generated by Django 3.2.7 on 2021-12-27 09:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('month', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subhead', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
