# Generated by Django 3.2.7 on 2021-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
