# Generated by Django 3.2.7 on 2021-12-31 06:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_bgimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='discount',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='discountsub',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
