# Generated by Django 3.2.7 on 2021-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211231_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discountimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
