# Generated by Django 3.2.7 on 2021-12-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_message_contact_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
