# Generated by Django 3.2.7 on 2021-12-27 07:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
