# Generated by Django 3.2.7 on 2021-12-27 07:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='title1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
