# Generated by Django 3.2.7 on 2021-12-27 08:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='details',
            new_name='details1',
        ),
        migrations.AddField(
            model_name='services',
            name='details2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='details3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
