# Generated by Django 3.2.7 on 2021-12-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211227_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='services',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
