# Generated by Django 3.2.7 on 2021-12-27 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('offer', models.BooleanField(default=False)),
                ('price', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secsub', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sectitle', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
