# Generated by Django 3.2.7 on 2021-12-30 11:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bgimgfoot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='section',
            name='bgimghead',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='section',
            name='bgtit',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
