# Generated by Django 3.2.7 on 2021-12-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='introimg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
