# Generated by Django 3.2.7 on 2021-12-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details1', models.TextField(max_length=300)),
                ('details2', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
