# Generated by Django 3.2.7 on 2021-12-25 13:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='details1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='details2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
