# Generated by Django 3.2.7 on 2021-12-26 20:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20211225_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
