# Generated by Django 3.2.7 on 2021-12-26 20:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='chooseus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('details1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('details2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('details1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('details2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
