# Generated by Django 3.2.7 on 2021-12-26 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20211227_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chooseus',
            old_name='details1',
            new_name='reason1',
        ),
        migrations.RenameField(
            model_name='chooseus',
            old_name='details2',
            new_name='reason2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='details1',
            new_name='reason1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='details2',
            new_name='reason2',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AddField(
            model_name='chooseus',
            name='reason3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='titler1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='titler2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='titler3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='reason3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='titler1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='titler2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='titler3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
