# Generated by Django 3.2.7 on 2021-12-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20211227_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseus',
            name='choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.aboutus'),
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.aboutus'),
        ),
    ]
