# Generated by Django 3.2.7 on 2021-12-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20211227_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooseus',
            name='choose',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.AddField(
            model_name='chooseus',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
