# Generated by Django 3.2.7 on 2021-12-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_chooseus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
