# Generated by Django 3.2.7 on 2021-12-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_aboutus_bgimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooseus',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='reason2',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='reason3',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='titler2',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='titler3',
        ),
    ]
