# Generated by Django 3.2.7 on 2021-12-31 06:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20211231_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='chooseustitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='title',
        ),
    ]
